AWSTemplateFormatVersion: '2010-09-09'
Description: S3 bucket to store the generated audio files

Parameters:
  BucketName:
    Description: The s3 bucket name
    Type: String
    Default: 'polly-audiofiles-bucket'

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: Allow
          Action:
            - s3:Get*
            - s3:List*
          Principal: '*'
          Resource: !Join ['', ['arn:aws:s3:::', !Ref Bucket, '/*']]

Outputs:
  BucketArn:
    Description: ARN of the the bucket
    Value: !GetAtt Bucket.Arn
