version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql-container
    ports:
      - 3306:3306
    volumes:
      - ./db/Chinook_Mysql.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: Chinook
      MYSQL_USER: user
      MYSQL_PASSWORD: password
